pool:
  vmImage: 'vs2017-win2016'
  
  
  variables:
  buildConfiguration: 'Release'
  
  - task: DotNetCoreInstaller@0
  inputs:
    version: '2.1.300'
    
    - task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'
    
    - task: PublishBuildArtifacts@1
